version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ls
      - pip3 install cmake
#      Builds ion-c
      - python install.py
      - ls amazon/ion/ion-c-build
      - ls amazon/ion/ion-c-build/lib/
      - ls amazon/ion/ion-c-build/include/
#      build wheels
      - python setup.py bdist_wheel
      - ls dist
artifacts:
  files:
    - dist/*.whl