version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo Installing............
      - ls
#      - pip3 install cmake

      - python install.py
      - ls amazon/ion/ion-c-build
      - ls amazon/ion/ion-c-build/lib/
      - ls amazon/ion/ion-c-build/include/

      - python setup.py bdist_wheel
      - ls
  post_build:
    commands:
      - echo "Build completed"