version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo Installing............
      - ls
      - pip3 install cmake
      - cmake --version
      - dir C:\
      - dir "C:\Program Files (x86)"
      - python install.py
      - ls amazon/ion/ion-c-build
      - ls amazon/ion/ion-c-build/lib/
      - ls amazon/ion/ion-c-build/include/
  post_build:
    commands:
      - echo "Build completed"