version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo Installing............
      - ls
      - pip3 install cmake
      - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"
      - set VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools
      - echo %VS150COMNTOOLS%
      - set
      - python install.py
      - ls amazon/ion/ion-c-build
      - ls amazon/ion/ion-c-build/lib/
      - ls amazon/ion/ion-c-build/include/
  post_build:
    commands:
      - echo "Build completed"