version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

  build:
    commands:
      - apt-get update
      - apt-get install python3.6
      - apt-get install python3.9
#      - ls
#      - pip3 install cmake
      #      Builds ion-c
#      - python install.py
#      - ls amazon/ion/ion-c-build/lib/
      #      build wheels
#      - python setup.py bdist_wheel
#      - python3.8 setup.py bdist_wheel
#      - python3.7 setup.py bdist_wheel
#      - python3.6 setup.py bdist_wheel
#      - ls dist
#artifacts:
#  files:
#    - dist/*.whl