version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:

  build:
    commands:
      - ls /opt
      - python3.7 --version
      - python3 --version
      - python3.8 --version

      #      - ls
#      - pip3 install cmake
      #      Builds ion-c
#      - python install.py
#      - ls amazon/ion/ion-c-build/lib/
      #      build wheels
#      - python setup.py bdist_wheel
#      - python3.8 setup.py bdist_wheel
#      - python3.7 setup.py bdist_wheel
#      - python3.6 setup.py bdist_wheel
#      - ls dist
#artifacts:
#  files:
#    - dist/*.whl